require_relative "common/BostonClamChowder"
require_relative "common/BostonFishChowder"
require_relative "common/ChickenSoup"
require_relative "common/ClamChowder"
require_relative "common/FishChowder"
require_relative "common/HonoluluClamChowder"
require_relative "common/HonoluluFishChowder"
require_relative "common/Minnestrone"
require_relative "common/PastaFazul"
require_relative "common/SoupBuffet"
require_relative "common/Soup"
require_relative "common/TofuSoup"
require_relative "common/VegetableSoup"

